# Generated by Django 4.1.2 on 2022-12-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bx", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Works",
            new_name="Work",
        ),
    ]
