# Generated by Django 4.1.2 on 2022-12-10 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bx", "0002_rename_works_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motion_name",
                    models.CharField(help_text="Motion Name", max_length=50),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="Source Link/Youtube Link", max_length=100
                    ),
                ),
                (
                    "date_uploaded",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        help_text="Date uploaded",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="work",
            name="file_name",
            field=models.CharField(
                help_text="Name *name must start with logo_, graphic_ or info_",
                max_length=50,
            ),
        ),
    ]
