# Generated by Django 4.1.2 on 2022-12-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bx", "0003_motion_alter_work_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motion",
            name="link",
            field=models.URLField(help_text="Source Link/Youtube Link"),
        ),
    ]
