# Generated by Django 4.1.2 on 2022-12-12 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bx", "0005_rename_link_motion_motion_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motion_name",
                    models.CharField(help_text="Motion Name", max_length=50),
                ),
                (
                    "linkThumbnail",
                    models.ImageField(help_text="Image", upload_to="bx/media"),
                ),
                ("motion_link", models.URLField(help_text="Youtube Link")),
                (
                    "date_uploaded",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        help_text="Date uploaded",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorksTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Name *name must start with logo_, graphic_ or info_",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(help_text="Image to show", upload_to="bx/media"),
                ),
                (
                    "serviceType",
                    models.CharField(
                        choices=[
                            ("Logo", "logo"),
                            ("Graphic Design", "graphics"),
                            ("Info Graphics", "info"),
                        ],
                        default=1,
                        help_text="Service Type",
                        max_length=50,
                    ),
                ),
                (
                    "date_uploaded",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        help_text="Date uploaded",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Motion",
        ),
        migrations.DeleteModel(
            name="Work",
        ),
    ]
