# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: name-tests-test
      # -   id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|json|markdown|md|yaml|yml)$

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.12.2
  #   hooks:
  #     - id: pylint

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  # - repo: https://github.com/psf/black
  #   rev: 21.12b0
  #   hooks:
  #     - id: black
