apiVersion: v1
kind: PersistentVolume
metadata:
  name: bx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bx-storage-class
  provisioner: kubernetes.io/aws-ebs
