apiVersion: v1
kind: PersistentVolume
metadata:
  name: bx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  ibm:
    csi:
      driver: ibm.io/ibmc-block-csi
  volumeClaimTemplates:
    - metadata:
        name: bx-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi