apiVersion: v1
kind: PersistentVolume
metadata:
  name: bx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibmc-block-silver
  volumeType: block
