apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bx-pvc
spec:
  storageClassName: gp2
  resources:
    requests:
      storage:  200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany