name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r brandxpert/requirements.txt
      - name: Install Doppler
        run: |
          echo "Install pre-reqs"
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
          echo "Add Doppler's GPG key"
          curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo apt-key add -
          echo "Add Doppler's apt repo"
          echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list
          echo "Fetch and install latest doppler cli"
          sudo apt-get update && sudo apt-get install -y doppler
      - name: Run Tests
        run: |
          doppler run -- pytest -v --cov && coverage report -m
